export const teamLogos: Record<string, string> = {
  "Atlanta Hawks": "https://loodibee.com/wp-content/uploads/nba-atlanta-hawks-logo.png",
  "Boston Celtics": "https://loodibee.com/wp-content/uploads/nba-boston-celtics-logo.png",
  "Brooklyn Nets": "https://loodibee.com/wp-content/uploads/nba-brooklyn-nets-logo.png",
  "Charlotte Hornets": "https://loodibee.com/wp-content/uploads/nba-charlotte-hornets-logo.png",
  "Chicago Bulls": "https://loodibee.com/wp-content/uploads/nba-chicago-bulls-logo.png",
  "Cleveland Cavaliers": "https://loodibee.com/wp-content/uploads/nba-cleveland-cavaliers-logo.png",
  "Dallas Mavericks": "https://loodibee.com/wp-content/uploads/nba-dallas-mavericks-logo.png",
  "Denver Nuggets": "https://loodibee.com/wp-content/uploads/nba-denver-nuggets-logo.png",
  "Detroit Pistons": "https://loodibee.com/wp-content/uploads/nba-detroit-pistons-logo.png",
  "Golden State Warriors": "https://loodibee.com/wp-content/uploads/nba-golden-state-warriors-logo.png",
  "Houston Rockets": "https://loodibee.com/wp-content/uploads/nba-houston-rockets-logo.png",
  "Indiana Pacers": "https://loodibee.com/wp-content/uploads/nba-indiana-pacers-logo.png",
  "Los Angeles Clippers": "https://loodibee.com/wp-content/uploads/nba-la-clippers-logo.png",
  "Los Angeles Lakers": "https://loodibee.com/wp-content/uploads/nba-los-angeles-lakers-logo.png",
  "Memphis Grizzlies": "https://loodibee.com/wp-content/uploads/nba-memphis-grizzlies-logo.png",
  "Miami Heat": "https://loodibee.com/wp-content/uploads/nba-miami-heat-logo.png",
  "Milwaukee Bucks": "https://loodibee.com/wp-content/uploads/nba-milwaukee-bucks-logo.png",
  "Minnesota Timberwolves": "https://loodibee.com/wp-content/uploads/nba-minnesota-timberwolves-logo.png",
  "New Orleans Pelicans": "https://loodibee.com/wp-content/uploads/nba-new-orleans-pelicans-logo.png",
  "New York Knicks": "https://loodibee.com/wp-content/uploads/nba-new-york-knicks-logo.png",
  "Oklahoma City Thunder": "https://loodibee.com/wp-content/uploads/nba-oklahoma-city-thunder-logo.png",
  "Orlando Magic": "https://loodibee.com/wp-content/uploads/nba-orlando-magic-logo.png",
  "Philadelphia 76ers": "https://loodibee.com/wp-content/uploads/nba-philadelphia-76ers-logo.png",
  "Phoenix Suns": "https://loodibee.com/wp-content/uploads/nba-phoenix-suns-logo.png",
  "Portland Trail Blazers": "https://loodibee.com/wp-content/uploads/nba-portland-trail-blazers-logo.png",
  "Sacramento Kings": "https://loodibee.com/wp-content/uploads/nba-sacramento-kings-logo.png",
  "San Antonio Spurs": "https://loodibee.com/wp-content/uploads/nba-san-antonio-spurs-logo.png",
  "Toronto Raptors": "https://loodibee.com/wp-content/uploads/nba-toronto-raptors-logo.png",
  "Utah Jazz": "https://loodibee.com/wp-content/uploads/nba-utah-jazz-logo.png",
  "Washington Wizards": "https://loodibee.com/wp-content/uploads/nba-washington-wizards-logo.png"
};
